function newsletterToAdmin(userName: string, userEmail: string): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Newsletter Subscriber</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            text-align: center;
            background-color: #006482;
            color: white;
            padding: 10px 0;
        }
        .header h1 {
            margin: 0;
        }
        .content {
            padding: 20px;
            text-align: center;
        }
        .content h2 {
            color: #006482;
        }
        .footer {
            text-align: center;
            padding: 20px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Jigglycard Admin Notification</h1>
        </div>
        <div class="content">
            <h2>New Newsletter Subscriber</h2>
            <p>Hello Admin,</p>
            <p>A new user has subscribed to the Jigglycard newsletter!</p>
            <p><strong>Username:</strong> ${userName}</p>
            <p><strong>User Email:</strong> ${userEmail}</p>
            <p>Make sure to welcome them and keep them updated on the latest news and offers.</p>
            <p>Thanks,</p>
            <p>The Jigglycard Notification System</p>
        </div>
        <div class="footer">
            <p>This is an automated notification generated by the Jigglycard website.</p>
        </div>
    </div>
</body>
</html>`;
}

export default newsletterToAdmin;
